### ISSUE TITLE
Basics about Pressure based Dispense System

### ISSUE THREAD

**Issue by DavidFederl** [ES-EDU-SIEGMA/Documentation#1]
## Description

Research on pressure based Systems to dispense liquids, like use in bars.

## ToDo

- [ ] Write a brief summery of the concept (How does it work?)
- [ ] Get some information about the costs of such systems 
- [ ] Note hardware requirements for this approach
