### ISSUE TITLE
Move from Gitlab to GitHub

### ISSUE THREAD

**Issue by DavidFederl** [ES-EDU-SIEGMA/Documentation#4]
## Description

Move all content from git.uni-due.de to github and set up the project.

## ToDo

- [x] Move Embedded Repository
- [x] Move UI Repository
- [x] Move Documentation
- [x] Move Recent Issues/User Stories
- [ ] Move Past Issues
